package com.hhzb.fntalm.module.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hhzb.fntalm.bean.Input;
import com.hhzb.fntalm.bean.Cabin;
import com.hhzb.fntalm.bean.Admin;
import com.hhzb.fntalm.bean.BackPut;
import com.hhzb.fntalm.bean.Num;

import com.hhzb.fntalm.module.db.InputDao;
import com.hhzb.fntalm.module.db.CabinDao;
import com.hhzb.fntalm.module.db.AdminDao;
import com.hhzb.fntalm.module.db.BackPutDao;
import com.hhzb.fntalm.module.db.NumDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig inputDaoConfig;
    private final DaoConfig cabinDaoConfig;
    private final DaoConfig adminDaoConfig;
    private final DaoConfig backPutDaoConfig;
    private final DaoConfig numDaoConfig;

    private final InputDao inputDao;
    private final CabinDao cabinDao;
    private final AdminDao adminDao;
    private final BackPutDao backPutDao;
    private final NumDao numDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        inputDaoConfig = daoConfigMap.get(InputDao.class).clone();
        inputDaoConfig.initIdentityScope(type);

        cabinDaoConfig = daoConfigMap.get(CabinDao.class).clone();
        cabinDaoConfig.initIdentityScope(type);

        adminDaoConfig = daoConfigMap.get(AdminDao.class).clone();
        adminDaoConfig.initIdentityScope(type);

        backPutDaoConfig = daoConfigMap.get(BackPutDao.class).clone();
        backPutDaoConfig.initIdentityScope(type);

        numDaoConfig = daoConfigMap.get(NumDao.class).clone();
        numDaoConfig.initIdentityScope(type);

        inputDao = new InputDao(inputDaoConfig, this);
        cabinDao = new CabinDao(cabinDaoConfig, this);
        adminDao = new AdminDao(adminDaoConfig, this);
        backPutDao = new BackPutDao(backPutDaoConfig, this);
        numDao = new NumDao(numDaoConfig, this);

        registerDao(Input.class, inputDao);
        registerDao(Cabin.class, cabinDao);
        registerDao(Admin.class, adminDao);
        registerDao(BackPut.class, backPutDao);
        registerDao(Num.class, numDao);
    }
    
    public void clear() {
        inputDaoConfig.getIdentityScope().clear();
        cabinDaoConfig.getIdentityScope().clear();
        adminDaoConfig.getIdentityScope().clear();
        backPutDaoConfig.getIdentityScope().clear();
        numDaoConfig.getIdentityScope().clear();
    }

    public InputDao getInputDao() {
        return inputDao;
    }

    public CabinDao getCabinDao() {
        return cabinDao;
    }

    public AdminDao getAdminDao() {
        return adminDao;
    }

    public BackPutDao getBackPutDao() {
        return backPutDao;
    }

    public NumDao getNumDao() {
        return numDao;
    }

}
